### ISSUE TITLE
What's your favorite way that you've celebrated an occasion?

### ISSUE THREAD

**Issue by simonv3** [RichardLitt/ama#12]
Any occasion.

**Comment by RichardLitt** [comment]
Every time I've come back to this question, I've thought of this one time. It's probably not my favorite, but it's what keeps coming to mind when I think about it. 

I ate an orange. 

I had just taken a year off from the University of Edinburgh to "go write that book", among other things. I hiked the West Highland Way with some friends, fell in love. I had one of the happiest moments of my life, sitting on a hill above Kinlochleven looking at the sunset. It looked like this:

![dsc_6459](https://cloud.githubusercontent.com/assets/910753/10088707/b240c252-62ea-11e5-82ca-5560dd136333.JPG)

I hiked to Inverness, three days on the Great Glen Way alone. After a few days in Edinburgh, I flew to Rome. 

This was my second time there. I flew with a cheap airline to Ciampino, a small airport around 7 miles outside of the city. Like the first time, I walked out of the airport, and past all of the buses waiting around to take people into the city. A few hundred meters down the road, a little dirt track led through some fields. Five minutes later, it joined a paved track heading into Rome - the Via Appia Antica, the old Roman Road. I walked at night down the road, saw my first groundhog. That night I slept in a graveyard next to the catacombs mentioned in _The Count of Monte Cristo_, the catacombs of St. Sebastian. I had one of the most horrifying nightmares of my life there. I was flying through a valley, hidden in a large range of mountains, and in the middle were three trees on a small hill. A guardian, in the fearsome shape of a Scottish terrier, was following my flight on the ground. He barked, and the wind in the valley became sentient, and knocked me out of the air to the ground so swiftly that I woke up in a cold sweat. 

I packed up my tent, and decided not to sleep in a cemetery again. Then I walked into Rome. I had a pizza slice next to Neptune's fountain, and then went to the banks of the Tiber, beneath the Vatican. It was almost noon. 

I took out an orange, and sat and looked at the sunlight on the marble walls. I lifted the first slice to my mouth. It was my 20th birthday.
