### ISSUE TITLE
Who's your role model?

### ISSUE THREAD

**Issue by zmbc** [RichardLitt/ama#18]

**Comment by RichardLitt** [comment]
I have a lot. 

I just read a couple of pages from Hamish's Mountain Walk, by [Hamish Brown](https://en.wikipedia.org/wiki/Hamish_Brown), about hiking all of the Munros on foot with only ferries and a bicycle. It is great reading, and I would love to do the same some day. My heart's been in the highlands a lot recently, and if I could, I would follow in Hamish's footsteps.
