### ISSUE TITLE
What do you use to write LaTeX?

### ISSUE THREAD

**Issue by nikivdev** [RichardLitt/ama#22]
Saw your [thesis](https://github.com/RichardLitt/thesis) and found it quite interesting. I am thinking of typesetting some of the notes I have in Tex.

I am curious what editor/tool you use writing LaTeX? Also what tools do you use for reference management?

I myself use VS Code with [LaTeX Workshop](https://marketplace.visualstudio.com/items?itemName=James-Yu.latex-workshop) extension.

**Comment by RichardLitt** [comment]
I use a [TeXShop](http://pages.uoregon.edu/koch/texshop/), and I often write the actual text files in Atom, but I compile in Texshop. Seems to work pretty well. I try not to spend too much time arguing with tex, and more time working on writing. For reference management, I use bibtex with texshop, too. 

Make sense?

**Comment by nikivdev** [comment]
Awesome. Yeah it does. 🙂
